config/routes.rb
ZPionka::Application.routes.draw do
  get "tomaiframes/new"

  get "tomaiframes/match_with_tournament"
  
  get "tomaiframes/match_and_back_to_iframe"
  
  get "tomaiframes/finish_or_open_broadcast"

  get "tomaiframes/create"

  get "tomaiframes/edit"

  get "tomaiframes/update"

  get "tomaiframes/show"

  get "tomaiframes/index"

  get "tomaiframes/delete"

  get "movecomments/new"

  get "movecomments/create"

  get "movecomments/index"

  get "movecomments/update"

  get "movecomments/edit"

  get "movecomments/destroy"

  get "uploads/new"

  get "uploads/index"

  get "uploads/show"

  get "uploads/create"

  get "uploads/destroy"

  get "newsletters/new"

  get "newsletters/create"

  get "newsletters/edit"

  get "newsletters/update"

  get "newsletters/show"

  get "newsletters/index"

  get "newsletters/send"

  get "zpawn/new"

  get "zpawn/create"

  get "zpawn/edit"

  get "zpawn/update"

  get "zpawn/index"

  get "zpawn/destroy"
  
  get "zpawn/show"

  get "pgn/add_pgn"

  get "allowances/new"

  get "allowances/edit"

  get "allowances/destroy"

  get "observes/new"

  get "observes/create"

  get "observes/destroy"

  get "observes/show"

  get "observes/index"

  get "gamechats/new"

  get "gamechats/create"

  get "gamechats/edit"

  get "gamechats/update"

  get "gamechats/show"

  get "gamechats/index"

  get "gamechats/destroy"

  get "positions/new"

  get "positions/create"

  get "positions/edit"

  get "positions/update"

  get "positions/index"

  get "positions/show"

  get "positions/destroy"

  get "rounds/new"

  get "rounds/create"

  get "rounds/update"

  get "rounds/edit"

  get "rounds/show"

  get "rounds/index"

  get "rounds/destroy"

  get "games/new"

  get "games/create"

  get "games/edit"

  get "games/destroy"

  get "games/index"

  get "games/show"
  
  get "games/read_pgn_file"
  
  get "games/show_games_in_java_window"

  get "games/update"

  get "players/new"

  get "players/create"
  
  get "players/list_all_games"

  get "players/edit"

  get "players/update"

  get "players/show"

  get "players/index"

  get "players/destroy"

  get "tourplaces/new"

  get "tourplaces/create"

  get "tourplaces/edit"

  get "tourplaces/update"

  get "tourplaces/show"

  get "tourplaces/indez"

  get "tourplaces/destroy"

  get "tourchats/new"

  get "tourchats/create"

  get "tourchats/index"

  get "tourchats/show"

  get "tourchats/edit"

  get "tourchats/update"

  get "tourchats/destroy"

  get "tournaments/new"

  get "tournaments/add_to_observed_and_redirect"
  
  get "tournaments/add_to_observed_games"
  
  get "tournaments/remove_from_observed_and_redirect"

  get "tournaments/create"

  get "tournaments/edit"

  get "tournaments/update"

  get "tournaments/show"

  get "tournaments/index"

  get "tournaments/destroy"

  get "comment/new"

  get "comment/create"

  get "comment/update"

  get "comment/edit"

  get "comment/show"

  get "comment/index"

  get "comment/destroy"

  get "messages/new"

  get "messages/create"

  get "messages/edit"

  get "messages/update"

  get "messages/index"

  get "messages/show"

  get "messages/destroy"

  get "info/new"

  get "info/create"

  get "info/show"

  get "info/index"

  get "info/update"

  get "info/destroy"
  
  get "info/delete"

  get "info/edit"
  get "user/new"
  get "user/create"
  get "user/update"
  get "user/edit"
  get "user/destroy"
  get "user/index"  
  get "info/index_user"
  get "session/new"
  get "page/home"
  
resources :tomaiframes 
resources :movecomments
resources :uploads 
resources :newsletters 
resources :allowances
resources :players
resources :zpawns
resources :tourchats
resources :gamechats
resources :tournaments
resources :tourplaces
resources :rounds
resources :comments  
resources :messages  
resources :users
resources :infos
resources :games
resources :sessions, :only => [:new, :create, :destroy]

match '/faq', :to => "pages#faq"
match '/broadcast_matching', :to => "tomaiframe#match_with_tournament"
match 'games/movecomments', :to => "games#_movecomment"
match 'games/variations', :to => "pages#_variations"
match 'user_send_message', :to => "users#mail_index"
match '/delete_comment', :to => "comments#destroy"
match '/signout', :to => "sessions#destroy"
match '/userlist', :to => "users#index" 
match '/infolist', :to => "infos#index" 
match '/add_to_observed_and_redirect', :to => "tournaments#add_to_observed_and_redirect"
match '/remove_from_observed_and_redirect', :to => "tournaments#remove_from_observed_and_redirect"
match '/add_to_observed_round_and_redirect', :to => "tournaments#add_to_observed_round_and_redirect"
match '/remove_from_observed_round_and_redirect', :to => "tournaments#remove_from_observed_round_and_redirect"
match '/add_to_observed_games', :to => "tournaments#add_to_observed_games"
match '/remove_from_observed_games', :to => "tournaments#remove_from_observed_games"
match '/list_all_games', :to => "players#list_all_games"

match '/unread_messages', :to => "messages#index"
match '/index_user', :to => "infos#index_user"
match '/add_pgn', :to => "pgn#add_pgn"
match '/parse_pgn', :to =>"pgn#parse_pgn"
match '/change_allowance', :to => "allowances#new"
match '/user_list', :to => "users#index"
match '/change_and_create', :to =>"allowances#change_and_create"


 root :to => "tournaments#index"


end

app/models/player.rb
class Player < ActiveRecord::Base
	
	default_scope :order => "surname ASC"
	
	validates :name, :presence => true
	validates :surname, :presence => true
	validates :rating, :numericality => true
	
	has_many :games
	has_many :tourplaces
	
	def merge_players(player1, player2)
		if compare_players(player1, player2)
			compared_players = player_with_more_games(player1, player2)
			@games_with_white = Game.find_all_by_player1_id(compared_players[1])
			@games_with_black = Game.find_all_by_player1_id(compared_players[1])
			
			@games_with_white.each do |game|
				game.player1_id = compared_players[0].id
				game.save
			end	
			
			@games_with_black.each do |game|
				game.player2_id = compared_players[0].id
				game.save
			end	
			
			Player.delete(compared_players[1].id)
			
			"Players matched - one was replaced"
		else 
			"Players don't match"	
		end	
		
		
	end	
	
	
	private
	def compare_players(player1, player2)
		player1.name == player2.name && player1.surname == player2.surname 
	end
	
	def player_with_more_games(player1, player2)
		if Game.find_all_by_player1_id(player1.id).size + Game.find_all_by_player2_id(player1.id).size >= Game.find_all_by_player1_id(player2.id).size + Game.find_all_by_player2_id(player2.id).size
			[player1,player2]
		else
			[player2,player1]
		end
	end
		 
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def new
  end

  def create
  end

  def edit
  	  	@player = Player.find(params[:id])
  	  	@title = "Editing player info"
  	
  end

  def update
  	
  @player = Player.find(params[:id])
  if @player.update_attributes(params[:player])
    flash[:success] = "Player succesfully updated."
    redirect_to @player
  else
    @title = "Edit player"
    render 'edit'
  end
    	
  end

  def show
  	@player = Player.find(params[:id])
  	@tournaments = find_tournament_with_player(@player,9)
  	@title = "Games of " + @player.surname + " " + @player.name
  	
  	@games_white = @tournaments[0]
  	@games_black = @tournaments[1]
  end
  
  def list_all_games
  	@player = Player.find(params[:id])
  	@tournaments = find_tournament_with_player(@player,10000)
  	@title = "Games of " + @player.surname + " " + @player.name
  	
  	@games_white = @tournaments[0]
  	@games_black = @tournaments[1]
  	
  end	

  def index
  	
  	@players = Player.paginate(:page => params[:page], :per_page => 15)
  	
  	
  	@title = "List of all players"
  	

  	
  end
  

  
  def destroy
  end

end

app/helpers/players_helper.rb
module PlayersHelper
	
def find_tournament_with_player(player,limit)
	@games_white = Game.find(  :all, :conditions => ["player1_id=?",player.id] , :limit => limit) 
	@games_black = Game.find(  :all, :conditions => ["player2_id=?",player.id] ,  :limit => limit)
	
	[@games_white,@games_black]	
end
	
end

app/views/players/create.html.erb
<h1>Players#create</h1>
<p>Find me in app/views/players/create.html.erb</p>

app/views/players/destroy.html.erb
<h1>Players#destroy</h1>
<p>Find me in app/views/players/destroy.html.erb</p>

app/views/players/edit.html.erb
<b>Edit player</b>

<%= form_for(@player) do |f| %>
	
<table>
<tr>
<td><%= f.label :Name %></td>
<td><%= f.text_field :name %></td>
</tr>

<tr>
<td><%= f.label :Surname %></td>
<td><%= f.text_field :surname %></td>
</tr>

  <%= f.hidden_field :rating, :value => @player.rating  %>
  
  <%= f.hidden_field :country, :value => @player.country  %>	
	
  
<tr><td>
<%= f.submit "Update" %></td>
</tr> 
</table>	
	
<% end %>

app/views/players/index.html.erb
<%= will_paginate @players %>

<table>
	<tr><td width="15%">Surname</td><td width="15%">Name</td><td width="10%">Rating</td><td width="10%">Games white</td><td width="10%">Games black</td><td width="10%">Wins</td><td width="10%">Draws</td><td width="10%">Losts</td></tr>
	<% @players.each do |player| %>
	
	<% @tournaments = find_tournament_with_player(player,10000) %>
  	<% @games_white = @tournaments[0] %>
  	<% @games_black = @tournaments[1] %>
  	
  	<% @wins = 0  %>
  	<% @draws = 0  %>
  	<% @losts = 0  %>
  	
  	<% @games_white.each do |game| %>
  		<% if game.result == "1" %>
  			<%	@draws += 1 %>
  		<% elsif game.result == "2" %>
  			 <% @losts += 1  %>
  		<% elsif game.result == "0" %>
  			<% @wins += 1  %>	
  		<% end %>
  	<% end %>
  	
   <% @games_black.each do |game| %>
  		<% if game.result == "1" %>
  			<%	@draws += 1 %>
  		<% elsif game.result == "0" %>
  			 <% @losts += 1  %>
  		<% elsif game.result == "2" %>
	  		<% @wins += 1  %>	
	  	<% end %>
  	<% end %>

	<tr>
		
		<td width="15%"><%= link_to player.surname.to_s, player %></td>
		<td width="15%"><%= link_to player.name.to_s, player %></td>
		<td width="10%"><%= player.rating %> </td>
		<td width="10%"><%= @games_white.size %></td>
		<td width="10%"><%= @games_black.size %></td>
		<td width="10%"><%= @wins %></td>
		<td width="10%"><%= @draws %></td>
		<td width="10%"><%= @losts %></td>
	
	
		</tr>
	<% end %>
</table>	

app/views/players/list_all_games.html.erb
<% @eye = image_tag("pictograms/eye.gif", :alt => "Observe", :class => "round") %>
<% @closed_eye = image_tag("pictograms/closed-eye.gif", :alt => "Observe", :class => "round") %>	
<% @goto = image_tag("pictograms/goto_icon.gif", :alt => "Go", :class => "round") %>	

<h4> Games of <%= @player.name + " " + @player.surname  %> </h4>

<table>
<tr><td>Player white</td><td>Player black</td><td>Result</td><td>Moves</td><td>Link</td><td>Observation</td></tr>
<% @games_white.each do |game| %>
<tr height="50%">
<td width="30%"><%= player(game,"white") %></td>
<td width="30%"><%= player(game,"black") %></td>
<td width="10%"><%= make_result(game.result) %></td>
<td width="10%"><%= game.positions.size/2 + ((2-game.result.to_i)/2) %></td>
<td width="10%"><%= link_to @goto ,game %> </td>

	<td width="10%">					
		<% if signed_in? && already_observed(game)%>
		<%= link_to @eye, :controller => "tournaments", :action => "remove_from_observed_games", :id => game.id , :confirm => "Are you sure you want to remove game from yourlist?" %>
		<% elsif signed_in? && !already_observed(game) %>
		<%= link_to @closed_eye,  :controller => "tournaments", :action => "add_to_observed_games", :id => game.id, :confirm => "Are you sure you want to observe this game?" %>
		<% end %>
		</td>
			
</tr>
<% end %>	
</table>

<table>
<tr><td>Player white</td><td>Player black</td><td>Result</td><td>Moves</td><td>Link</td><td>Observation</td></tr>
<% @games_black.each_with_index do |game,index| %>
<tr height="50%">
<td width="30%"><%= player(game,"white") %></td>
<td width="30%"><%= player(game,"black") %></td>
<td width="10%"><%= make_result(game.result) %></td>
<td width="10%"><%= game.positions.size/2 + ((2-game.result.to_i)/2) %></td>
<td width="10%"><%= link_to @goto ,game %> </td>

	<td width="10%">					
		<% if signed_in? && already_observed(game)%>
		<%= link_to @eye,  :controller => "tournaments", :action => "remove_from_observed_games", :id => game.id , :confirm => "Are you sure you want to remove game from yourlist?" %>
		<% elsif signed_in? && !already_observed(game) %>
		<%= link_to @closed_eye,  :controller => "tournaments", :action => "add_to_observed_games", :id => game.id, :confirm => "Are you sure you want to observe this game?" %>
		<% end %>
		</td>
			
</tr>
<% end %>	
</table>

app/views/players/new.html.erb
<h1>Players#new</h1>
<p>Find me in app/views/players/new.html.erb</p>

app/views/players/show.html.erb
<% @eye = image_tag("pictograms/eye.gif", :alt => "Observe", :class => "round") %>
<% @closed_eye = image_tag("pictograms/closed-eye.gif", :alt => "Observe", :class => "round") %>	
<% @goto = image_tag("pictograms/goto_icon.gif", :alt => "Go", :class => "round") %>	

<span class="h2_stripe"> Games of <%= @player.name + " " + @player.surname  %> </span><br/>
	
	<% if admin_in? %>
		<%= link_to "Edit user name", edit_player_path(@player) %><br/><br/>
	
	
	<% end %>
	

<span class="h3_stripe"> Games with white </span><br/>	
<table>
<tr><td>Player white</td><td>Player black</td><td>Result</td><td>Moves</td><td>Link</td><td>Observation</td></tr>
<% @games_white.each do |game| %>
	
<% moves = game.positions.maximum(:move_number) %>	
	
<tr>
<td width="30%"><%= player(game,"white") %></td>
<td width="30%"><%= player(game,"black") %></td>
<td width="10%"><%= make_result(game.result) %></td>
<td width="10%"><% moves %><%= game.positions.size/2 + ((2-game.result.to_i)/2) %></td>
<td width="10%"><%= link_to @goto ,game %> </td>

	<td width="10%">					
		<% if signed_in? && already_observed(game)%>
		<%= link_to @eye,  :controller => "tournaments", :action => "remove_from_observed_games", :id => game.id , :confirm => "Are you sure you want to remove game from yourlist?" %>
		<% elsif signed_in? && !already_observed(game) %>
		<%= link_to @closed_eye,  :controller => "tournaments", :action => "add_to_observed_games", :id => game.id, :confirm => "Are you sure you want to observe this game?" %>
		<% end %>
		</td>
			
</tr>
<% end %>	
</table>

<span class="h3_stripe"> Games with black </span><br/>	
<table>
<tr><td>Player white</td><td>Player black</td><td>Result</td><td>Moves</td><td>Link</td><td>Observation</td></tr>
<% @games_black.each_with_index do |game,index| %>
<tr>
<td width="30%"><%= player(game,"white") %></td>
<td width="30%"><%= player(game,"black") %></td>
<td width="10%"><%= make_result(game.result) %></td>
<td width="10%"><%= game.positions.size/2 + ((2-game.result.to_i)/2) %></td>
<td width="10%"><%= link_to @goto ,game %> </td>

	<td width="10%">					
		<% if signed_in? && already_observed(game)%>
		<%= link_to @eye,  :controller => "tournaments", :action => "remove_from_observed_games", :id => game.id , :confirm => "Are you sure you want to remove game from yourlist?" %>
		<% elsif signed_in? && !already_observed(game) %>
		<%= link_to @closed_eye,  :controller => "tournaments", :action => "add_to_observed_games", :id => game.id, :confirm => "Are you sure you want to observe this game?" %>
		<% end %>
		</td>
			
</tr>
<% end %>	
</table>

<%= link_to "List all his/hers games", :controller => "players", :action => "list_all_games", :id => @player.id %>

app/views/players/update.html.erb
<h1>Players#update</h1>
<p>Find me in app/views/players/update.html.erb</p>