config/routes.rb
ZPionka::Application.routes.draw do
  get "tomaiframes/new"

  get "tomaiframes/match_with_tournament"
  
  get "tomaiframes/match_and_back_to_iframe"
  
  get "tomaiframes/finish_or_open_broadcast"

  get "tomaiframes/create"

  get "tomaiframes/edit"

  get "tomaiframes/update"

  get "tomaiframes/show"

  get "tomaiframes/index"

  get "tomaiframes/delete"

  get "movecomments/new"

  get "movecomments/create"

  get "movecomments/index"

  get "movecomments/update"

  get "movecomments/edit"

  get "movecomments/destroy"

  get "uploads/new"

  get "uploads/index"

  get "uploads/show"

  get "uploads/create"

  get "uploads/destroy"

  get "newsletters/new"

  get "newsletters/create"

  get "newsletters/edit"

  get "newsletters/update"

  get "newsletters/show"

  get "newsletters/index"

  get "newsletters/send"

  get "zpawn/new"

  get "zpawn/create"

  get "zpawn/edit"

  get "zpawn/update"

  get "zpawn/index"

  get "zpawn/destroy"
  
  get "zpawn/show"

  get "pgn/add_pgn"

  get "allowances/new"

  get "allowances/edit"

  get "allowances/destroy"

  get "observes/new"

  get "observes/create"

  get "observes/destroy"

  get "observes/show"

  get "observes/index"

  get "gamechats/new"

  get "gamechats/create"

  get "gamechats/edit"

  get "gamechats/update"

  get "gamechats/show"

  get "gamechats/index"

  get "gamechats/destroy"

  get "positions/new"

  get "positions/create"

  get "positions/edit"

  get "positions/update"

  get "positions/index"

  get "positions/show"

  get "positions/destroy"

  get "rounds/new"

  get "rounds/create"

  get "rounds/update"

  get "rounds/edit"

  get "rounds/show"

  get "rounds/index"

  get "rounds/destroy"

  get "games/new"

  get "games/create"

  get "games/edit"

  get "games/destroy"

  get "games/index"

  get "games/show"
  
  get "games/read_pgn_file"
  
  get "games/show_games_in_java_window"

  get "games/update"

  get "players/new"

  get "players/create"
  
  get "players/list_all_games"

  get "players/edit"

  get "players/update"

  get "players/show"

  get "players/index"

  get "players/destroy"

  get "tourplaces/new"

  get "tourplaces/create"

  get "tourplaces/edit"

  get "tourplaces/update"

  get "tourplaces/show"

  get "tourplaces/indez"

  get "tourplaces/destroy"

  get "tourchats/new"

  get "tourchats/create"

  get "tourchats/index"

  get "tourchats/show"

  get "tourchats/edit"

  get "tourchats/update"

  get "tourchats/destroy"

  get "tournaments/new"

  get "tournaments/add_to_observed_and_redirect"
  
  get "tournaments/add_to_observed_games"
  
  get "tournaments/remove_from_observed_and_redirect"

  get "tournaments/create"

  get "tournaments/edit"

  get "tournaments/update"

  get "tournaments/show"

  get "tournaments/index"

  get "tournaments/destroy"

  get "comment/new"

  get "comment/create"

  get "comment/update"

  get "comment/edit"

  get "comment/show"

  get "comment/index"

  get "comment/destroy"

  get "messages/new"

  get "messages/create"

  get "messages/edit"

  get "messages/update"

  get "messages/index"

  get "messages/show"

  get "messages/destroy"

  get "info/new"

  get "info/create"

  get "info/show"

  get "info/index"

  get "info/update"

  get "info/destroy"
  
  get "info/delete"

  get "info/edit"
  get "user/new"
  get "user/create"
  get "user/update"
  get "user/edit"
  get "user/destroy"
  get "user/index"  
  get "info/index_user"
  get "session/new"
  get "page/home"
  
resources :tomaiframes 
resources :movecomments
resources :uploads 
resources :newsletters 
resources :allowances
resources :players
resources :zpawns
resources :tourchats
resources :gamechats
resources :tournaments
resources :tourplaces
resources :rounds
resources :comments  
resources :messages  
resources :users
resources :infos
resources :games
resources :sessions, :only => [:new, :create, :destroy]

match '/faq', :to => "pages#faq"
match '/broadcast_matching', :to => "tomaiframe#match_with_tournament"
match 'games/movecomments', :to => "games#_movecomment"
match 'games/variations', :to => "pages#_variations"
match 'user_send_message', :to => "users#mail_index"
match '/delete_comment', :to => "comments#destroy"
match '/signout', :to => "sessions#destroy"
match '/userlist', :to => "users#index" 
match '/infolist', :to => "infos#index" 
match '/add_to_observed_and_redirect', :to => "tournaments#add_to_observed_and_redirect"
match '/remove_from_observed_and_redirect', :to => "tournaments#remove_from_observed_and_redirect"
match '/add_to_observed_round_and_redirect', :to => "tournaments#add_to_observed_round_and_redirect"
match '/remove_from_observed_round_and_redirect', :to => "tournaments#remove_from_observed_round_and_redirect"
match '/add_to_observed_games', :to => "tournaments#add_to_observed_games"
match '/remove_from_observed_games', :to => "tournaments#remove_from_observed_games"
match '/list_all_games', :to => "players#list_all_games"

match '/unread_messages', :to => "messages#index"
match '/index_user', :to => "infos#index_user"
match '/add_pgn', :to => "pgn#add_pgn"
match '/parse_pgn', :to =>"pgn#parse_pgn"
match '/change_allowance', :to => "allowances#new"
match '/user_list', :to => "users#index"
match '/change_and_create', :to =>"allowances#change_and_create"


 root :to => "tournaments#index"


end

app/models/info.rb
class Info < ActiveRecord::Base
	
		validates :title, :presence => true, :length => { :within => 1..50 }
		validates :lead, :presence => true, :length => { :within => 1..100 }
		validates :short_content, :presence => true, :length => { :within => 1..700 }
		validates :content, :presence => true, :length => { :within => 1..30000 }		
		belongs_to :user
	
  def show_comments(id)
	Comment.find_all_by_info_id(id)
  end		
		
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  def new
    @title = "New info"
    @info = Info.new
    if !current_user.nil?
    	@user = current_user
    else
    	@user = User.new
    end
  end

  def create
  @user = current_user
  @info = Info.new(params[:info])
  if @info.save
    flash[:success] = "Succesfull adding"
    redirect_to @info
  else
    @title = "Add new info"
    render 'new'
  end
  end

  def show
  @info = Info.find(params[:id])
  @title = @info.title
  @user = User.find(@info.user_id)
  
  
  end

  def index
     @title = "Info list" 
     @info = Info.paginate(:page => params[:page])
  end


  def update
  @info = Info.find(params[:id])
  if @info.update_attributes(params[:info])
    flash[:success] = "Info succesfully updated."
    redirect_to @info
  else
    @title = "Edit info"
    render 'edit'
  end
  
  end
  
  def delete
  	
  end	

  def destroy
    Info.find(params[:id]).destroy
    flash[:success] = "Info destroyed."
    redirect_to infos_path
  end

  def edit
    @title = "Edit info"
    @info = Info.find(params[:id])
  end
  
  def index_user
  	@title = "User info list"
  end
  
end

app/helpers/info_helper.rb
module InfoHelper
	
   
	  
  def show_comments(id)
  	Comment.show_comments(id)
  end	
	
end

app/views/infos/create.html.erb
<h1>Info#create</h1>
<p>Find me in app/views/info/create.html.erb</p>

app/views/infos/destroy.html.erb
<h1>Info#destroy</h1>
<p>Find me in app/views/info/destroy.html.erb</p>

app/views/infos/edit.html.erb
<b>Edit form</b>
<%= form_for(@info) do |f| %>
<%= render 'shared/info_error_messages' %>

<table>
<tr>
<td><%= f.label :Title %></td>
<td><%= f.text_field :title %></td>
</tr>

<tr>
<td><%= f.label :Lead %></td>
<td><%= f.text_field :lead %></td>
</tr>


<tr>
<td><%= f.label :Short_summary %></td>
<td><%= text_area :info , :short_content, :size => "40x10"	  %></td>
</tr>


<tr>
<td><%= f.label :Content %></td>
<td><%= text_area :info , :content, :size => "40x20"	  %></td>
</tr>

<tr><td>
<%= f.submit "Save changes" %></td>
</tr>
</table>
<% end %>

app/views/infos/index.html.erb
<% @info = Info.find(:all, :order => "created_at DESC") %>
<% @info.each do |info| %>
	<% @user = User.find(info.user_id) %>

<%= info.updated_at.strftime("%d.%m.%Y") %>
<span class="info_title"><%= info.title %>&nbsp&nbsp(<%= link_to @user.login, @user %>)</span><br/>
<%= info.short_content %>&nbsp <%= link_to "More...", info %><br/><br/>




<%= link_to "Read info", info %>
(<%= comment_count = Comment.find(:all, :conditions => {:info_id => info.id}).size %>)


<% if admin_in? || signed_in? && current_user.id == info.user_id %>
| <%= link_to "Edit info", edit_info_path(info)%> |
<%= link_to "Delete info", info, :method => :delete, :confirm => "Are you sure?",
:title => "Delete #{info.title}" %>

<% end %>

<hr/>

<% end %>

app/views/infos/index_user.html.erb
<% @info = Info.find(:all, :order => "created_at DESC", :conditions => {:user_id => params[:id]}) %>
<% unless @info.empty? %>
<% @info.each do |info| %>

<strong><%= info.title %></strong><br/>
<%= info.short_content %><br/><br/>

<%= link_to "Read info", info %>


<% if admin_in? || signed_in? && current_user.id == @info.user_id %>
| <%= link_to "Edit info", edit_info_path(info)%> |
<%= link_to "Delete info", info, :method => :delete, :confirm => "Are you sure?",
:title => "Delete #{info.title}" %>

<% end %>

<hr/>
<% end %>

<% else %>
<h3><%= "No infos to display" %></h3> 

<% end %>
<%= link_to "Return to profile", current_user %>

app/views/infos/new.html.erb
<b>New article form: <%= @user.id %></b>
<%= form_for(@info) do |f| %>
<%= render 'shared/info_error_messages' %>

<table>
<tr>
<td><%= f.label :Title %></td>
<td><%= f.text_field :title %></td>
</tr>

<tr>
<td><%= f.label :Lead %></td>
<td><%= f.text_field :lead %></td>
</tr>


<tr>
<td><%= f.label :Short_summary %></td>
<td><%= text_area :info , :short_content, :size => "40x10"	  %></td>
</tr>


<tr>
<td><%= f.label :Content %></td>
<td><%= text_area :info , :content, :size => "40x20"	  %></td>
</tr>


<%= f.hidden_field :user_id, :value => @user.id %>

<tr><td>
<%= f.submit "Save" %></td>
</tr>
</table>
<% end %>

app/views/infos/show.html.erb
<%= @info.updated_at.strftime("%d.%m.%Y") %>

<span class="info_title"><%= @info.title %>&nbsp&nbsp(<%= link_to @user.login, @user %>)</span><br/><br/>
<% unless @info.lead==nil %>
<strong><%= @info.lead %></strong><br />
<% end%>
<% @info.short_content %><br/>

<%= @info.content %><br />
<hr/>

<% @comments = @info.show_comments(@info.id) %>
<% @comments.each do |comment| %>
<b>
<% @user_login = comment.find_user(comment.user_id) %>
<strong><%= link_to @user_login, User.find_by_login(@user_login) %></strong></b>
<% if comment.user_id == current_user.id || admin_in? %>

<%= link_to "Edit", edit_comment_path(comment,:info_id => @info.id)  %>
<%= link_to 'Delete', delete_comment_path(:id => comment.id), :confirm => "Are you sure" %>
	
<% end %>	
<br/><%= comment.content %>
<hr/>

<% end %>


<%= link_to "Add comment", new_comment_path(:info_id => @info.id) %>

app/views/infos/update.html.erb
<h1>Info#update</h1>
<p>Find me in app/views/info/update.html.erb</p>